name: 'Push'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bazel build //...
